services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0.30-debian
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
